### ISSUE TITLE
EPIC: Add rest of the endpoints from the schema

### ISSUE THREAD

**Issue by georgi-l95** [LimeChain/Hederium#5]
### Description
This EPIC will describe the effort for adding all missing endpoints, according to the schema

- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #33
- [ ] eth_getBalance: Returns the balance of an account at a given block.
- [ ] eth_getBlockByHash: Returns information about a block by its hash.
- [ ] eth_getBlockByNumber: Returns information about a block by its number.
- [ ] eth_getBlockTransactionCountByHash: Returns the number of transactions in a block by hash.
- [ ] eth_getBlockTransactionCountByNumber: Returns the number of transactions in a block by number.
- [ ] eth_getCode: Returns the contract code at a given address.
- [ ] eth_getLogs: Returns logs matching a given filter object.
- [ ] eth_getStorageAt: Returns the value at a storage position of a contract at a given block.
- [ ] eth_getTransactionByBlockHashAndIndex: Returns transaction info by block hash and transaction index.
- [ ] eth_getTransactionByBlockNumberAndIndex: Returns transaction info by block number and transaction index.
- [ ] eth_getTransactionByHash: Returns information about a transaction by its hash.
- [ ] eth_getTransactionCount: Returns the number of transactions sent from an address.
- [ ] eth_getTransactionReceipt: Returns the receipt of a transaction by transaction hash.
- [x] #31
- [x] #30
- [x] #28
- [x] #29
- [x] #27
- [x] #26
- [x] #25
- [ ] eth_newBlockFilter: Creates a filter to notify of new blocks.
- [ ] eth_newFilter: Creates a filter object for logs.
- [ ] eth_uninstallFilter: Uninstalls a given filter.
- [ ] eth_getFilterLogs: Returns all logs for a given filter ID.
- [ ] eth_getFilterChanges: Returns changes since the last filter check.
- [ ] eth_sendRawTransaction: Submits a raw transaction for execution.
- [x] #24
- [x] #16
- [x] #15
- [x] #14
- [ ] eth_subscribe: Creates a new subscription (used for WebSocket subscriptions).
- [ ] eth_unsubscribe: Cancels an existing subscription.
- [ ] debug_traceTransaction: Traces the execution of a transaction as it was executed on the network.
